import { defineConfig, presetWind3, transformerVariantGroup } from 'unocss'

// Pingr landing — UnoCSS config.
// Strategy: class names in .astro are UNCHANGED. Each is resolved either by a
// shortcut (direct properties, utility strings) or by the preflight block
// (pseudo-elements, ::first-child/:not/:nth-child, nested child selectors,
// media queries, keyframes, scrollbar, multi-layer gradients, :root tokens,
// reset). No external .css files remain — virtual:uno.css is the single source.

export default defineConfig({
  presets: [presetWind3()],
  transformers: [transformerVariantGroup()],
  // Classes built via template-literal concatenation in .astro (e.g.
  // class={`avatar${cond ? ' unread' : ''}`}) are NOT seen by UnoCSS's
  // content scanner — the base token sits flush against ${ and gets dropped.
  // Safelist forces these base shortcuts to generate regardless of scan,
  // so avatar/seg-i/ig-tile/pr-card get their base rule. Modifier classes
  // (unread/snoozed/soon/feat/max/on) are preflight compound rules, already
  // emitted via the preflight block, so only the BASE shortcuts need listing.
  safelist: [
    'avatar', 'seg-i', 'ig-tile', 'pr-card',
    // Language dropdown open-state variants — attribute + named-group combos
    // the scanner may miss; force-generate so the menu always shows/hides.
    'group-data-[open=true]/lang:opacity-100',
    'group-data-[open=true]/lang:translate-y-0',
    'group-data-[open=true]/lang:scale-100',
    'group-data-[open=true]/lang:pointer-events-auto',
    'group-data-[open=true]/lang:text-fg',
    'group-data-[open=true]/lang:rotate-180',
  ],
  theme: {
    // Colors reference the :root CSS vars so utilities (bg-bg, text-fg, ...)
    // stay in sync with var(--bg) used in inline styles and preflight CSS.
    colors: {
      bg: { DEFAULT: 'var(--bg)', raised: 'var(--bg-raised)', overlay: 'var(--bg-overlay)', hover: 'var(--bg-hover)', selected: 'var(--bg-selected)' },
      fg: { DEFAULT: 'var(--fg)', muted: 'var(--fg-muted)', dim: 'var(--fg-dim)' },
      border: { DEFAULT: 'var(--border)', strong: 'var(--border-strong)' },
      accent: { DEFAULT: 'var(--accent)', dim: 'var(--accent-dim)' },
      ai: { DEFAULT: 'var(--ai)', dim: 'var(--ai-dim)' },
      warn: 'var(--warn)',
      ch: {
        github: 'var(--ch-github)', gmail: 'var(--ch-gmail)', whatsapp: 'var(--ch-whatsapp)',
        slack: 'var(--ch-slack)', twitter: 'var(--ch-twitter)', facebook: 'var(--ch-facebook)',
        plane: 'var(--ch-plane)', telegram: 'var(--ch-telegram)', discord: 'var(--ch-discord)',
        linear: 'var(--ch-linear)', notion: 'var(--ch-notion)', jira: 'var(--ch-jira)', gitlab: 'var(--ch-gitlab)',
      },
      lp: { ink: 'var(--lp-ink)', line: 'var(--lp-line)', line2: 'var(--lp-line-2)' },
    },
    fontFamily: {
      sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
    },
    borderRadius: {
      sm: '6px', md: '10px', lg: '14px', pill: '9999px',
    },
  },
  preflights: [],
  shortcuts: {
    // ---- app-ui primitives (direct props) ----
    'popover': 'bg-bg border border-solid border-border-strong rounded-lg overflow-hidden shadow-[0_20px_60px_rgba(0,0,0,.5),0_0_0_1px_rgba(255,255,255,.04)]',
    'pop': 'h-full flex flex-col bg-bg',
    'topbar': 'flex items-center gap-[10px] px-[12px] py-[10px] border-b-1 border-b-solid border-b-border bg-bg-raised flex-none',
    'tb-logo': 'flex items-center gap-[8px] font-mono text-[11px] tracking-[.08em] text-fg',
    'tb-spacer': 'flex-1',
    'tb-ico': 'w-[26px] h-[26px] rounded-sm flex items-center justify-center cursor-pointer text-fg-muted transition-all duration-[180ms]',
    'search-lite': 'flex items-center gap-[8px] bg-bg-overlay border border-solid border-border rounded-sm px-[10px] py-[6px] flex-1 max-w-[220px]',
    'filters': 'flex gap-[6px] px-[12px] py-[10px] border-b-1 border-b-solid border-b-border bg-bg flex-none overflow-x-auto',
    'filter': 'font-sans text-[11px] text-fg-muted bg-transparent border border-solid border-border rounded-pill px-[10px] py-[4px] cursor-pointer inline-flex items-center gap-[5px] whitespace-nowrap transition-colors duration-[180ms]',
    'scroll': 'flex-1 overflow-visible py-[4px]',
    'sh': 'flex justify-between items-baseline px-[14px] pt-[18px] pb-[8px]',
    'sh-t': 'text-[15px] font-medium tracking-[-0.01em]',
    'sh-m': 'font-mono text-[10px] tracking-[.05em] text-fg-muted',
    'row': 'flex items-center',
    'nrow': 'grid grid-cols-[26px_1fr_auto] gap-[10px] mx-[10px] mb-[8px] px-[12px] py-[10px] bg-bg-raised border border-solid border-border rounded-md overflow-hidden shadow-[0_1px_2px_rgba(0,0,0,.4),0_8px_24px_rgba(0,0,0,.25)] items-start transition-colors duration-[180ms] relative',
    'avatar': 'w-[26px] h-[26px] rounded-full bg-bg-overlay border border-solid border-border flex items-center justify-center text-[10px] font-medium text-fg relative flex-none',
    'snooze-chip': 'inline-flex items-center gap-[4px] font-mono text-[9.5px] tracking-[.05em] text-accent bg-[rgba(125,200,255,.1)] border border-solid border-[rgba(125,200,255,.25)] rounded-pill px-[7px] py-[2px]',
    'rb': 'min-w-0',
    'rt': 'flex justify-between items-baseline gap-[10px]',
    'rt-l': 'font-mono text-[9.5px] tracking-[.05em] text-fg-muted whitespace-nowrap overflow-hidden text-ellipsis',
    'rt-r': 'font-mono text-[9.5px] tracking-[.05em] text-fg-dim whitespace-nowrap flex-none',
    'rti': 'text-[13px] font-medium leading-[1.35] mt-[2px] text-fg whitespace-nowrap overflow-hidden text-ellipsis',
    'rpv': 'text-[11.5px] text-fg-muted leading-[1.4] mt-[1px] whitespace-nowrap overflow-hidden text-ellipsis',
    'chip-ch': 'inline-flex items-center gap-[5px]',
    'statusbar': 'flex justify-between items-center px-[14px] py-[8px] border-t-1 border-t-solid border-t-border bg-bg-raised font-mono text-[10px] tracking-[.05em] text-fg-muted flex-none',
    'seg': 'inline-flex bg-bg-overlay border border-solid border-border rounded-pill p-[2px] gap-[2px]',
    'seg-i': 'font-mono text-[10px] tracking-[.05em] text-fg-muted px-[10px] py-[3px] rounded-pill cursor-pointer whitespace-nowrap',
    'sh-hd': 'px-[14px] pt-[14px] pb-[10px] border-b-1 border-b-solid border-b-border flex items-center gap-[10px]',
    'sug-group': 'px-[14px] pt-[12px] pb-[4px]',
    'sug-label': 'font-mono text-[10px] tracking-[.05em] text-fg-dim mb-[8px]',
    'snooze-inline': 'mx-[10px] mb-[8px] px-[14px] py-[12px] bg-bg-overlay border border-solid border-border rounded-md shadow-[0_1px_2px_rgba(0,0,0,.4),0_8px_24px_rgba(0,0,0,.25)]',
    'cbtn': 'bg-bg-raised text-fg border border-solid border-border rounded-pill px-[10px] py-[5px] text-[11.5px] cursor-pointer',
    'macbar': 'bg-[#0A0B0D] rounded-t-lg px-[14px] py-[6px] flex items-center justify-between font-sans text-[12px] text-[#D0D3D8] border border-solid border-[#1C1E23] [border-bottom:none]',
    'composer': 'flex-none flex items-center gap-[8px] px-[12px] py-[10px] border-t-1 border-t-solid border-t-border bg-bg-raised',
    'brief': 'px-[14px] pt-[16px] pb-[2px]',
    'brief-head': 'flex items-center justify-between gap-[12px] mb-[10px]',
    'brief-date': 'font-mono text-[10px] tracking-[.05em] text-fg-dim whitespace-nowrap',
    'brief-greet': 'text-[22px] font-medium tracking-[-0.02em] mb-[10px]',
    'brief-card': 'relative bg-[linear-gradient(180deg,rgba(198,184,244,.06),rgba(198,184,244,0)_55%)] bg-bg-raised border border-solid border-border rounded-md p-[16px] shadow-[0_1px_2px_rgba(0,0,0,.4),0_8px_24px_rgba(0,0,0,.25)] overflow-hidden',
    'brief-body': 'text-[14px] leading-[1.62] text-fg',
    'brief-meta': 'flex items-center gap-[8px] mt-[14px] pt-[12px] border-t-1 border-t-solid border-t-border font-mono text-[10px] tracking-[.05em] text-fg-dim',
    'ai-mod': 'mx-[10px]',
    'ai-mod-h': 'flex items-baseline justify-between gap-[12px] pt-[18px] px-[4px] pb-[8px]',
    'ai-mod-t': 'inline-flex items-baseline gap-[7px] text-[15px] font-medium tracking-[-0.01em]',
    'ai-mod-m': 'font-mono text-[10px] tracking-[.05em] text-fg-muted',
    'ai-list': 'bg-bg-raised border border-solid border-border rounded-md overflow-hidden shadow-[0_1px_2px_rgba(0,0,0,.4),0_8px_24px_rgba(0,0,0,.25)]',
    'task-row': 'grid grid-cols-[16px_1fr_auto] gap-[11px] px-[12px] py-[11px] border-t-1 border-t-solid border-t-border items-start',
    'check': 'w-[15px] h-[15px] rounded-[5px] border border-solid border-border-strong mt-[2px] flex-none relative cursor-pointer transition-all duration-[180ms]',
    'task-src': 'flex items-center gap-[6px] mt-[3px] font-mono text-[10px] tracking-[.03em] text-fg-muted',
    'task-when': 'font-mono text-[10px] text-fg-dim tracking-[.05em] whitespace-nowrap mt-[2px]',
    'watch-row': 'grid grid-cols-[16px_1fr_auto] gap-[11px] px-[12px] py-[11px] border-t-1 border-t-solid border-t-border items-start',
    'sev': 'w-[15px] h-[15px] flex-none mt-[1px] text-warn',
    'watch-when': 'font-mono text-[10px] tracking-[.05em] whitespace-nowrap text-warn mt-[2px] tabular-nums',
    'remind-row': 'grid grid-cols-[62px_1fr_16px] gap-[10px] px-[12px] py-[11px] border-t-1 border-t-solid border-t-border items-center',
    'remind-time': 'font-mono text-[11px] text-accent tracking-[.03em] tabular-nums whitespace-nowrap',
    'remind-t': 'text-[13px] text-fg leading-[1.4] min-w-0',
    'remind-ico': 'w-[15px] h-[15px] flex-none text-fg-dim justify-self-end',
    'chat': 'flex-1 overflow-y-auto p-[14px] pt-[16px] flex flex-col gap-[15px]',
    'msg': 'flex gap-[9px] max-w-full',
    'ava': 'w-[24px] h-[24px] rounded-full flex-none flex items-center justify-center bg-[linear-gradient(160deg,rgba(198,184,244,.28),rgba(198,184,244,.05))] border border-solid border-ai-dim text-ai mt-[2px]',
    'bubble': 'text-[13.5px] leading-[1.55] px-[13px] py-[11px] rounded-[14px_14px_14px_4px] bg-[linear-gradient(180deg,rgba(198,184,244,.05),transparent_60%)] bg-bg-raised border border-solid border-border max-w-[80%]',
    'src': 'inline-flex items-center gap-[6px] font-mono text-[10px] tracking-[.02em] text-fg-muted bg-bg border border-solid border-border rounded-full px-[8px] py-[3px] cursor-pointer',
    'suggest': 'flex flex-wrap gap-[6px] mt-[10px]',
    'sg': 'font-sans text-[12px] text-fg bg-bg border border-solid border-border-strong rounded-full px-[11px] py-[6px] cursor-pointer transition-colors duration-[160ms]',

    // ---- landing.css (direct props for simple classes) ----
    'lp-wrap': 'max-w-[1200px] mx-auto px-[clamp(20px,5vw,44px)]',
    'lp-eyebrow': 'font-mono text-[11px] tracking-[.14em] text-fg-muted inline-flex items-center gap-[8px]',
    'lp-h1': 'text-[clamp(40px,6.4vw,74px)] font-semibold tracking-[-0.035em] leading-[1.0] m-0 text-balance',
    'lp-h2': 'text-[clamp(28px,3.6vw,44px)] font-semibold tracking-[-0.03em] leading-[1.06] m-0 text-balance',
    'lp-lead': 'text-[clamp(16px,1.5vw,19px)] text-fg-muted leading-[1.6] m-0 max-w-[52ch]',
    'lp-accent': 'text-accent',
    'lp-lilac': 'text-ai',
    'lp-btn': 'inline-flex items-center gap-[8px] cursor-pointer font-sans font-semibold text-[14px] rounded-[10px] px-[18px] py-[11px] border border-solid border-transparent transition-all duration-[180ms] no-underline whitespace-nowrap',
    'lp-brand': 'flex items-center gap-[9px] font-mono text-[13px] tracking-[.06em] text-fg no-underline',
    'lp-hero': 'relative pt-[clamp(56px,9vw,104px)] pb-[clamp(40px,6vw,64px)] text-center overflow-hidden',
    'lp-pill': 'inline-flex items-center gap-[8px] pt-[5px] pr-[12px] pb-[5px] pl-[8px] border border-solid border-lp-line2 rounded-full bg-[rgba(255,255,255,.02)] text-[12.5px] text-fg-muted',
    'lp-scene': 'relative mt-[clamp(36px,5vw,60px)] mx-auto max-w-[1000px]',
    'lp-strip': 'py-[36px] border-y-1 border-y-solid border-y-lp-line',
    'lp-logos': 'flex flex-wrap gap-[10px_12px] justify-center',
    'lp-logo': 'inline-flex items-center gap-[8px] px-[13px] py-[7px] border border-solid border-lp-line rounded-full bg-bg-raised text-[13px] text-fg',
    'lp-section': 'py-[clamp(64px,9vw,116px)]',
    'lp-feature': 'grid grid-cols-[1.02fr_.98fr] gap-[clamp(32px,5vw,72px)] items-center',
    'lp-copy': 'flex flex-col gap-[18px] max-w-[520px]',
    'lp-ul': 'list-none flex flex-col gap-[12px] mt-[4px]',
    'lp-stats': 'flex gap-[28px] flex-wrap mt-[6px]',
    'lp-stat': 'text-[26px] font-semibold tracking-[-.02em]',
    'lp-pillars': 'grid grid-cols-4 gap-[16px] mt-[clamp(36px,5vw,56px)]',
    'lp-pillar': 'border border-solid border-lp-line rounded-[14px] px-[20px] py-[22px] bg-bg-raised flex flex-col gap-[10px]',
    'lp-intgrid': 'grid grid-cols-4 gap-[10px]',
    'lp-final': 'text-center relative overflow-hidden',
    'lp-footer': 'border-t-1 border-t-solid border-t-lp-line py-[44px]',
    'ig-split': 'grid grid-cols-[1.05fr_.95fr] gap-[clamp(32px,5vw,72px)] items-center',
    'ig-copy': 'flex flex-col gap-[16px] max-w-[460px]',
    'ig-head': 'text-center max-w-[640px] mx-auto flex flex-col gap-[16px] items-center',
    'ig-grid': 'grid grid-cols-4 gap-[10px]',
    'ig-tile': 'relative flex flex-col items-center gap-[9px] pt-[16px] px-[8px] pb-[13px] border border-solid border-border rounded-[13px] bg-bg-raised transition-all duration-[180ms] overflow-hidden',
    'ig-logo': 'w-[30px] h-[30px] flex items-center justify-center',
    'ig-legend': 'flex flex-wrap gap-[12px_24px] justify-center mt-[clamp(30px,4vw,42px)] text-[13px] text-fg-muted',
    'pr-head': 'text-center max-w-[640px] mx-auto flex flex-col gap-[16px] items-center',
    'pr-toggle': 'inline-flex gap-[4px] p-[4px] border border-solid border-[var(--lp-line-2)] rounded-full bg-bg-raised mt-[4px]',
    'pr-grid': 'grid grid-cols-3 gap-[16px] items-stretch mt-[clamp(36px,5vw,52px)]',
    'pr-card': 'relative flex flex-col gap-[13px] px-[24px] py-[30px] border border-solid border-border rounded-[18px] bg-bg-raised',
    'pr-badge': 'absolute top-[-11px] left-1/2 -translate-x-1/2 font-mono text-[9.5px] tracking-[.08em] text-lp-ink bg-accent rounded-full px-[12px] py-[4px] whitespace-nowrap',
    'pr-name': 'text-[18px] font-semibold tracking-[-.01em]',
    'pr-tagline': 'text-[13px] text-fg-muted mt-[-9px]',
    'pr-price': 'flex items-baseline gap-[1px] mt-[6px]',
    'pr-bill': 'font-mono text-[10px] tracking-[.05em] text-fg-dim mt-[-4px]',
    'pr-feat': 'list-none flex flex-col gap-[11px] mt-[8px] pt-[18px] border-t-1 border-t-solid border-t-border',
    'pr-note': 'text-center mt-[26px] font-mono text-[11px] tracking-[.05em] text-fg-dim',
    'cr-card': 'max-w-[760px] mx-auto border border-solid border-border rounded-[20px] p-[clamp(24px,4vw,44px)] bg-[radial-gradient(90%_80%_at_50%_-10%,rgba(125,200,255,.06),transparent_55%)] bg-bg-raised',
    'cr-head': 'flex flex-col gap-[12px] items-center text-center max-w-[560px] mx-auto mb-[clamp(24px,3vw,32px)]',
    'cr-form': 'flex flex-col gap-[14px]',
    'cr-row': 'grid grid-cols-2 gap-[14px]',
    'cr-field': 'flex flex-col gap-[6px]',
    'cr-label': 'font-mono text-[10.5px] tracking-[.05em] text-fg-muted flex items-center gap-[4px]',
    'cr-help': 'text-[11.5px] text-fg-dim leading-[1.4]',
    'cr-actions': 'flex items-center justify-end gap-[16px] flex-wrap mt-[2px]',
    'cr-status': 'text-[13px] text-fg-muted',
    'tagchip': 'absolute left-[16px] top-[16px] font-mono text-[10px] tracking-[.06em] text-fg-muted bg-[rgba(0,0,0,.35)] border border-solid border-lp-line rounded-full px-[10px] py-[4px]',
  },
})
